---
- hosts: webservers
  become: true
  vars:
    ansible_become_pass: jenkins
  tasks:
    - name: install tomcat and tomcat dependencies
      ansible.builtin.yum:
        name:
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
          - tomcat-docs-webapp
        state: present
    - name: start tomcat
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: yes
...