---
- hosts: webservers
  tasks:
    - name: install chronyd
      ansible.builtin.yum:
        name: chrony
        state: present
 
    - name: Start and enable chronyd service
      ansible.builtin.service:
        name: chronyd
        state: started
        enabled: yes

...
