---
# tasks file for httpd
- name: install httpd
  ansible.builtin.yum:
    name: httpd
    state: installed

- name: start and enable httpd
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: copy html to webservers
  ansible.builtin.copy:
    src: /root/index.html
    dest: /var/www/html/index.html